# -*- coding: utf-8 -*-
"""Copia de Copia de seminario ia

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u9xMLpAgM85Z_6PX66_G5v4vsLr-Kvd2
"""

print("===================================")
print("      CHATBOT ACADÉMICO")
print("===================================")
print("Consultas disponibles:")
print("- inscripciones")
print("- notas")
print("- horarios")
print("- correlativas")
print("- finales")
print("- becas")
print("- campus")
print("- biblioteca")
print("- certificado")
print("- faltas")
print("- asistencia")
print("- trámites")
print("- materias")
print("- cursada")
print("- promedio")
print("- título")
print("- equivalencias")
print("- correo institucional")
print("- plan de estudios")
print("- carrera")
print("Escriba 'salir' para finalizar")
print("===================================")

respuestas = {

    "inscripciones":
    """Las inscripciones se realizan desde SIU Guaraní.
Link: https://guarani.uba.ar""",

    "inscripcion":
    """Las inscripciones se realizan desde SIU Guaraní.
Link: https://guarani.uba.ar""",

    "notas":
    """Las notas pueden visualizarse desde SIU Guaraní.
Link: https://guarani.uba.ar""",

    "horarios":
    """Los horarios se encuentran publicados por la facultad.
Link: https://www.uba.ar""",

    "correlativas":
    """Las correlativas pueden consultarse en el plan de estudios.
Link: https://www.uba.ar""",

    "finales":
    """Las fechas de finales se publican en el calendario académico.
Link: https://www.uba.ar""",

    "becas":
    """La información sobre becas está disponible en Bienestar Estudiantil.
Link: https://www.uba.ar/becas""",

    "campus":
    """El acceso al campus virtual se realiza con usuario institucional.
Link: https://campusvirtual.uba.ar""",

    "biblioteca":
    """La biblioteca funciona de lunes a viernes.
Link: https://www.uba.ar""",

    "certificado":
    """El certificado de alumno regular puede descargarse desde SIU Guaraní.
Link: https://guarani.uba.ar""",

    "faltas":
    """Las faltas permitidas dependen del reglamento de cada materia.""",

    "asistencia":
    """La asistencia es registrada por cada docente.""",

    "tramites":
    """Los trámites académicos se realizan en Secretaría de Alumnos.
Link: https://www.uba.ar""",

    "materias":
    """La oferta de materias puede consultarse en el plan de estudios.
Link: https://www.uba.ar""",

    "cursada":
    """La información sobre cursadas está disponible en SIU Guaraní.
Link: https://guarani.uba.ar""",

    "promedio":
    """El promedio académico puede consultarse desde tu historial académico en SIU Guaraní.
Link: https://guarani.uba.ar""",

    "titulo":
    """El trámite de título se realiza mediante la Secretaría Académica.
Link: https://www.uba.ar""",

    "equivalencias":
    """Las equivalencias deben solicitarse mediante expediente académico.
Link: https://www.uba.ar""",

    "correo":
    """El correo institucional es otorgado por la universidad.""",

    "mail":
    """El correo institucional es otorgado por la universidad.""",

    "plan":
    """El plan de estudios puede consultarse en la página oficial de la carrera.
Link: https://www.uba.ar""",

    "planes":
    """Los planes de estudio están disponibles en la página oficial de la facultad.
Link: https://www.uba.ar""",

    "estudio":
    """El plan de estudios contiene las materias, correlativas y carga horaria de la carrera.
Link: https://www.uba.ar""",

    "carrera":
    """La información de la carrera y su plan de estudios puede consultarse en la página oficial.
Link: https://www.uba.ar"""
}

while True:

    consulta = input("\nUsuario: ").lower()

    if consulta == "salir":
        print("\nChatbot: Gracias por utilizar el sistema.")
        break

    encontrada = False

    for clave, respuesta in respuestas.items():

        if clave in consulta:

            print("\nChatbot:")
            print(respuesta)

            encontrada = True
            break

    if not encontrada:

        print("\nChatbot: No encontré información sobre esa consulta.")
        print("Pruebe con palabras como: notas, inscripciones, becas, finales, horarios, plan de estudios, carrera, trámites, etc.")